import smtplib
from email.mime.text import MIMEText
# from email.mime.multipart import MIMEMultipart


FROM = 'laxminarayana3101@gmail.com'
TO = "laxminarayanapattanayak@gmail.com"
SUBJECT = "Demo python mail sent"
TEXT = "This message was sent by Laxmi Narayana for test purpose."



message = MIMEText(TEXT)
message['From'] = FROM
message['To'] = TO
message['Subject'] = SUBJECT

SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 587


USERNAME = 'laxminarayana3101@gmail.com'
PASSWORD = '_____'  # A 16 alphabetic character based password generated by google account




try:
   
    server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
    server.starttls()
    server.login(USERNAME, PASSWORD)
    server.sendmail(FROM, TO, message.as_string())

    print("Email sent successfully!")
    
except Exception as e:
    print(f"Failed to send email: {e}")
    
finally:
    server.quit()