import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os

FROM = 'laxminarayana3101@gmail.com'
TO = "laxminarayanapattanayak@gmail.com"
SUBJECT = "Demo python mail with attachment"
TEXT = "This message was sent by Laxmi Narayana for test purpose with attachment."


message = MIMEMultipart()
message['From'] = FROM
message['To'] = TO
message['Subject'] = SUBJECT


message.attach(MIMEText(TEXT, 'plain'))

filename = os.path.basename(os.path.abspath('image.jpg'))  
print(filename)


with open(filename, 'rb') as attachment:
    part = MIMEBase('application', 'octet-stream')
    part.set_payload(attachment.read())
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', f'attachment; filename={filename}')
    message.attach(part)

SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 587

USERNAME = 'laxminarayana3101@gmail.com'
PASSWORD = '______'  # A 16 alphabetic character based password generated by google account


try:
    server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
    server.starttls()
    server.login(USERNAME, PASSWORD)
    server.sendmail(FROM, TO, message.as_string())
    print("Email sent successfully!")
except Exception as e:
    print(f"Failed to send email: {e}")
finally:
    server.quit()
